Mapping FeatureMapEntries to JSON
eclipse-emfcloud/emfjson-jackson pull request #67
Opened 2024-06-13 15:15 UTC by vhemery

Provide a mapping for FeatureMapEntries with JSON.
Dedicated Serializer and Deserializer handle the mapping and deserializer has a specific reference entries resolution.

The "Nora'sCaravan" model is a fully functional model which illustrates the problematic and could not be mapped with the old approach.

Note this changes the fragment paths in JsonResource:
Since the JSON and XMI paths to elements can not correspond, URI fragment is different in JSON and XMI.
(we can not have the same path since JSON does not allow duplicates nor specific properties ordering)
This specific fragment path is handled correctly by the JsonResource implementation.

This mapping comes with two flavors, configurable with the EMFModule.Feature.OPTION_USE_FEATURE_MAP_KEY_AND_VALUE_PROPERTIES option:
- using the feature name as the entry's key (lighter default option).
- using "featureName" for name of the feature and "value" for the feature value composing the entry.
Both options are illustrated in the example and tests.

Closes https://github.com/eclipse-emfcloud/emfjson-jackson/issues/8

2024-06-13 15:43 UTC, vhemery commented
@martin-fleck-at I don't get why my caravan.xcore's Package class is not generated and found by the tests.
Any idea ? (works on my machine)

2024-06-14 07:14 UTC, vhemery commented
> @martin-fleck-at I don't get why my caravan.xcore's Package class is not generated and found by the tests. Any idea ? (works in Eclipse, but not with Maven)

Apparently, the use of XML String type was not supported. ¯\_(ツ)_/¯
I wanted to simulate an XSD import, but that's not a big deal. So let's just use ecore String.

2024-06-15 18:37 UTC, martin-fleck-at commented
@vhemery Thank you very much for your PR, I'll have a proper look at it early next week.

2024-06-17 14:57 UTC, martin-fleck-at requested changes
Hi @vhemery, I had a look at the changes and they look really great to me. Thank you very much for the detailed comments and the additional test cases. The changes in the `JsonResource` only seem to affect the feature map part so I don't see any reason why we would not have backwards compatibility or did I overlook something? I left a few comments but nothing major. Thank you again for the great work.

2024-06-17 14:57 UTC, martin-fleck-at commented on src/main/java/org/eclipse/emfcloud/jackson/databind/property/EObjectFeatureProperty.java
> +   public void deserializeValue(final JsonParser jp, final EObject current, final DeserializationContext ctxt,
nit: Should they be public or is `protected` enough?

2024-06-18 07:35 UTC, martin-fleck-at commented
@vhemery Thank you for the quick update and the great work, everything looks good to me now.

2024-06-18 07:37 UTC, merged